# Generated by Django 3.2 on 2021-04-24 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='last_name',
            new_name='content',
        ),
    ]
