# Generated by Django 3.2 on 2021-05-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='fullname',
            field=models.CharField(help_text='Enter you surname', max_length=250),
        ),
    ]
