# Generated by Django 3.2 on 2021-05-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20210508_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='test',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
