# Generated by Django 3.2 on 2021-05-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_category_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='test',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
