# Generated by Django 3.2 on 2021-04-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_page_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='alias',
            field=models.CharField(default='default', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
